version: "3"

volumes:
  facetime_local_postgres_data: {}
  facetime_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: facetime_local_django
    container_name: facetime_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: facetime_production_postgres
    container_name: facetime_local_postgres
    volumes:
      - facetime_local_postgres_data:/var/lib/postgresql/data
      - facetime_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: docker.io/redis:6
    container_name: facetime_local_redis

  webdb:
    image: webdb/app
    container_name: facetime_local_webdb
    restart: always
    volumes:
      - "$HOME/.webdb:/usr/src/app/static/version"
    environment:
      SCAN_HOSTS: postgres
    ports:
      - "127.0.0.1:22071:22071"

  celeryworker:
    <<: *django
    image: facetime_local_celeryworker
    container_name: facetime_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: facetime_local_celerybeat
    container_name: facetime_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: facetime_local_flower
    container_name: facetime_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
