# Generated by Django 5.0.2 on 2024-02-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interestedingender',
            unique_together={('gender', 'user')},
        ),
    ]
