# Generated by Django 5.0.2 on 2024-03-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_blocked_profiles_customuser_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='blocked_profiles',
            new_name='blocked',
        ),
    ]
