# Generated by Django 5.0.2 on 2024-03-01 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_blocked_profiles_customuser_blocked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interestedinrelation',
            unique_together={('relationship', 'user')},
        ),
    ]
