# Generated by Django 5.0.3 on 2024-03-04 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='location_min_distance',
        ),
    ]
